### PR TITLE
fix: [#264] Allow configuration of containerSecurityContext.

### PR DESCRIPTION
**Pull request by 030**

### CODE REVIEW

**Comment by 030** [comment]
@mjtrangoni Could you review and release a newer version of the prometheus-msteams helm chart?

**Comment by mjtrangoni** [comment]
I am not the mantainer here. @kbudde FYI

**Comment by 030** [comment]
@kbudde Could you review?

**Comment by zhan9san** [comment]
@030 

Thanks for your contribution.

Could you help add document in https://github.com/prometheus-msteams/prometheus-msteams/tree/master/chart/prometheus-msteams?

**Comment by 030** [comment]
@zhan9san Updated the documentation. Could you review again please?

**Review by zhan9san — APPROVED** [review]

**Comment by 030** [comment]
@zhan9san Thank you for the approval. Could you merge the PR please?

**Comment by zhan9san** [comment]
@030 

Can you take a look at the `golangci-lint` issue?

**Comment by 030** [comment]
@zhan9san Updated. Could you start the CI again?

**Pull request merged**
