### PR TITLE
adding Helm/Sprig functions

### PR DESCRIPTION
**Pull request by universam1**
The functions include all functions (except 'env' and 'expandenv' ) from sprig (http://masterminds.github.io/sprig/)
and the following functions from HELM templating:
  - toToml
  - toYaml
  - fromYaml
  - toJson
  - fromJson

This should pave the way to more user friendly templating experience known from Helm widely

#56 #99

### CODE REVIEW

**Comment by universam1** [comment]
@krische @bzon

**Comment by bzon** [comment]
There is a work in progress code by @Knappek that may conflict with this. @Knappek please check. :)

**Comment by Knappek** [comment]
btw, @AndreasKnapp1812 is me, just my corporate github handle ^^

**Comment by Knappek** [comment]
close in favor of #128

**Pull request closed without merging**
