### PR TITLE
Add Grafana Alert inspired card template to examples 

### PR DESCRIPTION
**Pull request by trallnag**
### Description

resolves https://github.com/prometheus-msteams/prometheus-msteams/issues/158

Unrelated to all other changes: Updated screenshot of notification card in MS Teams to reflect changes implemented in https://github.com/prometheus-msteams/prometheus-msteams/pull/157 and mentioned here https://github.com/prometheus-msteams/prometheus-msteams/issues/156.

Add card template that produces a card that is quite similar to the one used by Grafana:

screenshot_card_template_grafana_group

The main characteristic is that alerts are grouped (at least) by the alert name and that the respective card lists all the values / legends of time series that matched the alert expression. I recommend to use this template when you can expect multiple series to match simultaneously.

The template file also includes a "fallback" that is used when the common annotation `template` is not `group`. In addition, a few more requirements must be met to make the template work. For example the annotation `value` that holds the formatted value of every series. All this is required because we cannot define the template directly in the alert rule.

screenshot_card_template_grafana_fallback

The README in examples was updated with screenshots, example alert rules and a short info text. A detailed listing of all requirements can be found in the template itself as a comment.

### Checklist

- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by trallnag** [comment]
resolves https://github.com/prometheus-msteams/prometheus-msteams/issues/158

**Comment by trallnag** [comment]
WIP, I'm considering removing the "fallback" and with that simplifying the template.

**Comment by Knappek** [comment]
@trallnag is this still WIP? I like the example and would like to merge it to master soon. Two comments:
- the last screenshot in the README is truncated: you can read `See more`, which looks confusing. 
- could you please add a table of contents in the readme? (there are plugins in vscode, vim etc. available - check out the main README for comparison)

**Comment by trallnag** [comment]
Hey @Knappek, sry for the delay. I implemented the docs related changes and the PR can be merged if I haven't missed anything. 

I considered extending the example template to be more "responsive" (for example extracting links automatically, showing a notice if an alert is split into multiple groups, removing non-specific labels and annotations, etc.) but after some time I ended up with a massive template file with more than 500 LoCs. So I think this is something better suited for a proper script in Python / Golang

**Comment by Knappek** [comment]
@trallnag looks good so far. There is only one thing, for me it does not correctly escape `>` signs:
image

Any idea why?

**Comment by trallnag** [comment]
@Knappek, I have probably messed something up regarding using an already escaped test payload while also requiring auto escape for the template. I'll take a look at it this night I think

**Comment by trallnag** [comment]
Ok so the issue was that the included `payload.json` for testing was already once escaped by prometheus-msteams

**Review by Knappek — APPROVED** [review]

**Comment by Knappek** [comment]
Thank you @trallnag, looks good now.

**Pull request merged**
