### PR TITLE
Helm Chart: Add envFrom to Helm chart

### PR DESCRIPTION
**Pull request by heubeck**
closes https://github.com/prometheus-msteams/prometheus-msteams/issues/172
Tested with and without existingEnvsSecret, working fine ;)

@Knappek | @bzon may you please have a look.

BTW: Thanks for this awesome project!

### CODE REVIEW

**Comment by Knappek** [comment]
@heubeck thanks for this PR. Currently I am not really working, I will get back to this PR once I have some spare time.

**Comment by Knappek** [comment]
closes #172

**Comment by Knappek** [comment]
Hi @heubeck my vacation is over ;). 

Thank you very much for your contribution!

I have a suggestion how to improve it: Your current implementation only allows to have one environment variable set and fetched from a secret (with the `secretRef` key). How about make the usage of `envFrom` more generic? As `envFrom` is an array, we could implement it similar to `extraEnvs` and then also allow to have it referenced a configmap with `configMapRef`. Does that make sense?

**Comment by heubeck** [comment]
Hi @Knappek, welcome back ;)
did I get you right, you suggest to have a list (`secretRefs: []`) that all become `envFrom` entries?
Can make that, sure.
Just wondering whether there are use cases where multiple secrets should be injected.
If you prefer that I'll update the PR.

**Comment by Knappek** [comment]
Kind of. How about being able to have something like this in `values.yaml`:

```yaml
envFrom:
  - configMapRef:
       name: some-config
  - configMapRef:
       name: some-other-config
  - secretRef:
       name: some-secret
  - secretRef:
       name: some-other-secret
  - ...
```

Does that make sense? 

Not sure whether there will be use cases for something like that, but people do a lot of stuff ;). If you don't agree or if this is too hard to implement, then let me know and we can perfectly go for your current solution and adapt it if some further needs arise.

**Comment by heubeck** [comment]
Ah, you just want me, to have `envFrom: {}` in values and
```
envFrom:
	{{- toYaml .Values.configuration | nindent 4 }}
```
in the deployment?
Yeah, that's maximal flexible and much simpler.
Will do.

**Comment by heubeck** [comment]
Thanks @Knappek for your feedback.
Updated according to your wishes, works like a charm ;)

**Review by Knappek — APPROVED** [review]
That's really awesome, I did not know about `envFrom` before, I learned something new, thanks again @heubeck !

**Pull request merged**
