### PR TITLE
[Security] Get rid of CVE's in binary & Docker image - Replace Alpine in favour of scratch

### LINKED ISSUE #236: [Security] Images have Vulnerabilitys
Image v1.4.2 has 1 Vulnerability:

image

Image v1.5.0 has 10 Vulnerabilitys:
image

Is it possible to update the Images?

For now i´m using v1.4.2 which seems okay for now with 1 minor Vulnerability.
But a "clean" Image would be fine :) .

### PR DESCRIPTION
**Pull request by JoooostB**
Resolves #236 
Both the binary as the version of Alpine used had some CVE's as described in #236. This PR gets rid of all CVE's by upgrading some packages and using a scratch container as runtime environment instead of Alpine.

By switching to scratch the container also gets even smaller than it already was :)

### CODE REVIEW

**Comment by bzon** [comment]
@Knappek this looks fine to me.

**Comment by Knappek** [comment]
@bzon looks good to me. Feel free to merge.

**Review by totoroot — APPROVED** [review]

**Comment by totoroot** [comment]
@Knappek @bzon @JoooostB Please merge, as the vulnerability is still open.

**Comment by JoooostB** [comment]
@totoroot Any chance you could build and push it to Quay as well?

**Pull request merged**
