### PR TITLE
Allow setting name of ConfigMap used for card template.

### PR DESCRIPTION
**Pull request by forsberg**
This makes it simpler to override the card template
when installing the chart via helmfile, or any other
way where you're not using a parent chart.

If there's a simpler way to do this, I'm happily educated :-)

### CODE REVIEW

**Comment by Knappek** [comment]
@forsberg I have tested your changes. Here some more comments:
* the `/healthz` endpoint does not work, I always get a `404 page not found`
* the general functionality works but as mentioned above, a little bit of documentation in the readme would be nice

**Comment by forsberg** [comment]
Thanks for feedback, will have a look one of the coming weeks (busy with other projects right now)

**Comment by bzon** [comment]
Hello @forsberg. What’s the healthz endpoint for? If it’s purpose is for just health checking, we already have the config handler  which can return 200 status code. :)

**Comment by Knappek** [comment]
@forsberg have you checked @bzon's comment?

**Comment by forsberg** [comment]
> @forsberg have you checked @bzon's comment?

Yes, and I find it highly relevant :-)

The time for fixing has unfortunately not materialized, but it's on my list.

**Comment by forsberg** [comment]
Closing this as the functionality for customizing the message has been extended, and we were able to solve our problem that way instead (with --set-file in Helm)

**Comment by bzon** [comment]
@forsberg please also look at the new feature for custom card per webhook. 👍

**Pull request closed without merging**
